### PR TITLE
proposal: Generic command buffers

### PR DESCRIPTION
**Pull request by udoprog**
[Rendered](https://github.com/udoprog/rfcs/blob/generic-command-buffers/text/0020-generic-command-buffers.md)

### CODE REVIEW

**Comment by udoprog** [comment]
Note that I would personally want to add a `Commands::defer(T)` to defer sending a message. This is particularly useful when you want to [defer an action in the constructor](https://github.com/udoprog/ontv/blob/8cca058/src/application.rs#L122). But I'm holding off with that for the first version and I don't think it needs a separate RFC.

**Comment by cryptoquick** [comment]
Nice work! I like it.

**Comment by hecrj** [comment]
This approach gets us away from the functional, composable style of the Elm Architecture by introducing an additional mutable argument that is meant to be mutated through side-effects.

I understand the main motivation here is performance, but in my experience commands are very rarely returned and hardly a bottleneck in `iced` applications. `map` calls are also relatively rare and, since a flat structure is recommended, the nesting levels should rarely be high enough to cause noticeable overhead.

The APIs of `Element` and `Command` are very analogous (in fact, `Element`'s performance is way more important) and introducing differences in them will cause inconsistencies.

**Comment by hecrj** [comment]
Also, if you wanted to, it's possible to avoid the `map` allocation overhead with the current API. Simply pass a closure as an argument.

Given `component`:

```rust
fn update<T>(f: impl Fn(Message) -> T) -> Command<T> {
    Command::perform(some_action().map(Message::ActionFinished), f)
}
```

You can call it from any parent:

```rust
enum Message {
    Component(component::Message),
}

component::update(Message::Component)
```

This is very similar to the proposed approach in the RFC.

**Comment by udoprog** [comment]
Thanks for the response. Since this is an RFC I'll take the opportunity to discuss a bit!

> This approach gets us away from the functional, composable style of the Elm Architecture by introducing an additional mutable argument that is meant to be mutated through side-effects.

Elm is a functional language, so it's necessary to use a functional approach to accomplish certain things - drawbacks included.

If we back up a step this change is primarily a limited form of inversion of control which is needed to do some things. But it doesn't actually change the high level capabilities of the API.

It's like changing this:

```rust
fn function() -> Vec<u32>;
```

Into this:

```rust
fn function(output: &mut Vec<u32>);
```

The former has to build a vector (which sometimes requires allocations) to call. The latter allows the caller to decide whether the passed in vector should be pristine or not - the inversion of control mentioned above. But there's nothing you can do with the former which you can't do with the latter. But the latter is necessary to for example allow the caller to pre-allocate the vector.

> The APIs of Element and Command are very analogous (in fact, Element's performance is way more important) and introducing differences in them will cause inconsistencies.

I've been considering building a [syntree](https://docs.rs/syntree) like structure to represent the UI trees in iced, specifically to reduce allocation pressure there as well. But it would itself be a major deviation from its functional style (the tree builder API would either have to be passed in or provided through thread-locals).

Final question would be: would something convince you to adopt this change or do you think I should just abandon it?

**Comment by hecrj** [comment]
`iced` is opinionated and inspired by Elm; the functional approach is preferred.

With `iced`'s philosophy, we prefer to think about producing independent building blocks that can be easily composed and put together (like LEGO!) rather than focusing on mutating existing (global) data structures. We are aware this has a performance impact, but we believe the tradeoff is worth it most of the time.

This RFC proposes a change that affects ergonomics of the public API and goes against this philosophy.

The main motivation here is performance. So, in order to justify a deviation from the philosophy of the library, we would need to have compelling evidence that the performance improvement is well worth it (benchmarks of realistic applications!) AND that there is no other viable approach that would maintain the current ergonomics (like using `smallvec`).

**Comment by udoprog** [comment]
Just to emphasize: I actually argued in the RFC that ergonomics was improved in two instances as well:
* The constructor no longer returns a tuple (so it becomes more like a normal Rust constructor).
* No need to figure out how to return `Command::none()` ([example improvement here](https://github.com/udoprog/iced/commit/fc0f0f501aae4ab5d819af7b14ab1ebe8d1b8d00#diff-e252a94bb3ca7de5fb10bcda3f9ced9170b8c6260ff06deb275f99d5f7779227)).

> With iced's philosophy, we prefer to think about producing independent building blocks that can be easily composed and put together (like LEGOs!) rather than focusing on mutating existing (global) data structures.

So I want to push back on this mentality a bit: It's not a global data structure *and* this sacrifices nothing in terms of composition - only how it is performed! The caller of the function decides what to pass in and how it should be composed. The *only* difference is who is responsible for constructing the buffer: the caller or the callee. This is even perfectly in line with *pure* functional programming - imagine that the command buffer is passed in and returned:

```rust
fn function(commands: Commands) -> Commands {
    commands.push(/* build command here */)
}
```

But in Rust we have the ability to use mutable references (in this RFC being abstracted over using a trait) which guarantees exclusive access inside of the called function - just as much as passing it in by value would. But we no longer have to suffer the ergonomics hit (or style choice) of having to return it.

```rust
fn function(commands: &mut Commands) {
    commands.push(/* build command here */);
}
```

**Comment by udoprog** [comment]
Also note: Since this wasn't completely shut down (all though it's hard to budge someone on philosophy ;). I'll share the benchmarks I did of my own application. I will have to rewrite it back into the existing iced so it'll take a minute. I'm maintaining a fork of iced ([see patch section here for how to use](https://github.com/udoprog/ontv/blob/main/Cargo.toml#L54)) if someone else has something they want to try out.

**Comment by hecrj** [comment]
I am aware they can be used without the data structures being global. That is why I put "global" in parentheses.

I don't believe you are pushing against the mentality with those two examples. It is certainly possible to code with a mutation-heavy mindset in functional languages. Both the examples you provided use (or emulate) mutation. Since we have mutability in Rust, it does make sense to use mutable references for that.

However, the current API does neither use nor emulate mutation of any sort. This is the point! Why bother with a mutation-based approach at all?

**Comment by hecrj** [comment]
> The constructor no longer returns a tuple (so it becomes more like a normal Rust constructor).

I'm not sure there is anything considered a "normal Rust constructor".

> No need to figure out how to return Command::none()

This could be seen as a disadvantage as well, since the compiler will no longer warn you about returning a `Command` for your messages.

**Comment by udoprog** [comment]
> I don't believe you are pushing against the mentality with those two examples. It is certainly possible to code with a mutation-heavy mindset in functional languages. Both the examples you provided use (or emulate) mutation. Since we have mutability in Rust, it does make sense to use mutable references for that.
>
> However, the current API does neither use nor emulate mutation of any sort. This is the point! Why bother with a mutation-based approach at all?

I'm not tracking this statement :thinking: - the push command was intended to showcase modifying an existing data structure by [returning a modified copy of it](https://elmprogramming.com/list.html) (or the `push` can take ownership of its argument, accomplishing the same thing). Or are you against APIs which modify immutable data structures as well in iced? Is this limited to dealing with commands?

I must admit that I don't make much of a functional or use distinction with the above and `Command::batch` (a `Command` really is just a complicatedly structured sequence and `batch` functionally concatenates them), but it seems like you do?

**Comment by hecrj** [comment]
> Or are you against APIs which modify immutable data structures as well in iced?

I'm not against it when mutation seems like the most organic approach (i.e. when it's explicit!). Most widgets use this approach, for instance.

> I must admit that I don't make much of a functional or use distinction with the above and Command::batch (a Command really is just a complicatedly structured sequence and batch functionally concatenates them), but it seems like you do?

The main difference is the mindset, or how you think about code.

The immutable approach gives complete control to the user of the API to compose the child `Command` in any way they please. A `Command` is a composable, self-contained piece of a puzzle. The user of the API must write code that explicitly connects and integrates the resulting `Command` somewhere.

The mutable approach is the complete opposite. In practice, you provide a mutable argument and the function mutates it in a completely hidden way. These sneaky mutations are, in the end, side effects.

Through experience, I have learned that side effects generally make code harder to understand and reason about. Everything tends to be less explicit and the responsibilities and boundaries of functions blur out. The same data can change in many different places.

**Comment by udoprog** [comment]
So I think I've understood the last part of the confusion: Using an argument like this to me is not a side effect. Provided the exact same argument with the exact same state you will be getting the exact same effect from calling the function completely encapsulated by the functions inputs and outputs. A mutable argument *in Rust* (where shared mutability is disallowed) is simply just an input and an output at the same time. And the proposed API in this RFC ensures that only a handful of things can happen with the argument: You can push commands and "perform" futures. No side effects involved*.

> *: The caller of the function *has to decide what to do with the mutated argument*. Just like it has to decide what to do with a returned `Command`. A caller could for example declare it's own local command buffer if it doesn't want to submit modifications to its own mutable argument directly.

The mindset you're proposing seems *more* to me: you categorically don't seem to like mutable arguments and want to avoid them. While I'm not entirely sure what the purported benefit is - ultimately you decide. I'll bring you the benchmarks so you at least get a better idea of the performance you'd be leaving on the table without any changes and then you can make the most informed decision possible. Beyond that this doesn't seem like the best forum to debate such an entrenched philosophical position of the project (hit me up on Discord?).

**Comment by hecrj** [comment]
The function is mutating state outside of its own scope. To me, that is a side effect. You call the function and some state outside of it has been changed. There has been an effect be*side*s calling the function and getting a result.

Not that it matters, but [Wikipedia](https://en.wikipedia.org/wiki/Side_effect_(computer_science)) agrees (emphasis mine):

> Example side effects include modifying a [non-local variable](https://en.wikipedia.org/wiki/Non-local_variable), modifying a [static local variable](https://en.wikipedia.org/wiki/Static_local_variable), __modifying a mutable argument [passed by reference](https://en.wikipedia.org/wiki/Evaluation_strategy#Call_by_reference)__, performing [I/O](https://en.wikipedia.org/wiki/I/O) or calling other functions with side-effects.

However, I don't think the meaning of "side effect" is that relevant here.

> Provided the exact same argument with the exact same state you will be getting the exact same effect from calling the function completely encapsulated by the functions inputs and outputs

If you have a function `f` that takes a mutable argument, then:

```rust
let some_ref = &mut some_data;

let a = f(some_ref);
let b = f(some_ref);
```

`f` is called twice with the exact same argument (the same mutable reference), and yet `a` and `b` can definitely be different based on that argument. This is the kind of sneaky mutation I am against, specially when the name of the function makes it unclear that an argument is being mutated. The mutation happens completely hidden inside of `f`!

Sure. You could say that `some_ref` changes state in the first call and therefore the second call doesn't really have the same argument... But the code doesn't reflect that at all!

> And the proposed API in this RFC ensures that only a handful of things can happen with the argument: You can push commands and "perform" futures. No side effects involved*.

Yes, but the coding style will still be one based on mutation instead of explicitly plumbing and connecting results. We want to encourage the latter.

> The mindset you're proposing seems more to me: you categorically don't seem to like mutable arguments and want to avoid them.

That's not right. I would like to avoid mutable arguments when possible, specially if the mutation of the argument isn't the only purpose of the function. In other words, when the mutations are side effects!

**Comment by udoprog** [comment]
Do note that you're citing something written in 1994 (before Rust), what you'll probably find more informative on the subject is a point of view which takes [Rust's ownership system into account](https://stackoverflow.com/questions/59696588/what-do-move-semantics-imply-for-referential-transparency-in-rust). Particularly the effect of how mutable references require exclusive access which is why I'd be much more wary of such a system in C (or Java) than I am with something similar in Rust.

**Comment by udoprog** [comment]
> f is called twice with the exact same argument (the same mutable reference), and yet a and b can definitely be different based on that argument. This is the kind of sneaky mutation I am against, specially when the name of the function makes it unclear that an argument is being mutated. The mutation happens completely hidden inside of f!

Note that the proposed command buffer API does not expose anything that allows `f` to have any divergent behaviors (there is no way to read the state of the buffers). I emphasised this before: you can only push commands. So the only question in your example for the actual API being proposed is whether the first call pushed any commands. And the only observable difference in behavior that can ever be possible with the proposed API is the order of execution that the buffered commands have.

To me, different orderings is both a benign effect and not something the current API prevents - since order depends on the order which things are provided to Command batch.

**Comment by hecrj** [comment]
You focus on the current RFC, but I have been talking for a while about the philosophy of the library and the coding style we want our users to work with.

Do we agree that the second approach you describe (seen as a coding style!) in [this comment](https://github.com/iced-rs/rfcs/pull/20#issuecomment-1376378113) has downsides? You seem to be comparing passing and returning a mutable value to passing a mutable reference as if they were equivalent because of Rust's borrow checker. [As I have shown above](https://github.com/iced-rs/rfcs/pull/20#issuecomment-1376605091), the state changes are no longer obvious in the code with the second approach.

If we agree there, then you should understand why I am against it.

The first approach you describe (i.e. emulating mutation) would be fine, but the impact on ergonomics would be huge. I'd say we would need the same amount of compelling evidence for adopting any of them.

Why bother with mutation-based approaches at all (emulated or not)? Why not focus on improving the current immutable approach? Also, what prompted this RFC? Did you hit a bottleneck in the use of `Command`? Why are we even considering changing this? What is the real problem we are trying to solve here?

**Comment by hecrj** [comment]
> Do note that you're citing something written in 1994 (before Rust), what you'll probably find more informative on the subject is a point of view which takes [Rust's ownership system into account](https://stackoverflow.com/questions/59696588/what-do-move-semantics-imply-for-referential-transparency-in-rust). Particularly the effect of how mutable references require exclusive access which is why I'd be much more wary of such a system in C (or Java) than I am with something similar in Rust.

Since the code I wrote above is perfectly valid, I am quite wary of such a system in Rust as well.

**Comment by udoprog** [comment]
I reached out on Discord if you want to continue talking about the philosophical differences since that seems like a better format for it.

For the rest I'll provide this thread with the profiling once I can find the time to rewrite my application again.

**Pull request closed without merging**
