### PR TITLE
proposal: SVG Theming

### PR DESCRIPTION
**Pull request by mmstick**
[Rendered](https://github.com/mmstick/iced-rfcs/blob/svg-themes/text/0015-svg-theming.md)

### CODE REVIEW

**Review by hecrj — COMMENTED** [review]
I'm not sure we need additional code to support this use case.

It seems we are trying to support SVG templating here, which I believe should be implemented at the SVG level instead of the rendering level.

For instance, you could have template SVG files with a placeholder value or a `#{color}` literal and then replace the value programatically in Rust before creating an `svg::Handle` with [`from_memory`](https://docs.iced.rs/iced/widget/svg/struct.Handle.html#method.from_memory).

Would that work?

**Comment by mmstick** [comment]
This doesn't work for the COSMIC use case because system icons aren't templates. We're loading icons in a similar fashion as Qt and GTK does on Linux. We use the [freedesktop-icons crate](https://crates.io/crates/freedesktop-icons) to dynamically search for icons from freedesktop standard icon paths, such as `/usr/share/icons`. The full list of locations searched is in the `XDG_DATA_DIRS` environment variable.

libcosmic detects the systems' icon theme preference and then requests to locate icons from that theme. So loading the `window-minimize-symbolic` icon would locate it at  `/usr/share/icons/Pop/scalable/actions/window-minimize-symbolic.svg` during runtime. These don't have readily accessible placeholder values within them . Easier to apply a filter after the image is rendered than parsing and re-creating the SVG in memory on load (and holding multiple cached copies of different variants of the SVGs).

This can also apply to icons which are PNGs, so similar behavior would be required for those icons, but virtually all icons in icon themes are available as SVGs these days, so it's not much of an issue.

Theme support is also necessary because these icons will have multiple variations based on activities like hovering over an interactive container changing the icon color to contrast with the change of the background color,  or an icon being shown as insensitive with a grey filter applied to it such as a button that's disabled.

**Comment by hecrj** [comment]
Would it be possible for you to parse the SVG and replace all the colors with the desired fill color before feeding that to `iced`?

Since the implementation here is just completely overwriting non-transparent pixels with the fill color, it seems that approach would be equivalent and wouldn't need changes to `iced`.

> Easier to apply a filter after the image is rendered than parsing and re-creating the SVG in memory on load (and holding multiple cached copies of different variants of the SVGs).

I'm not sure it's easier. Rendering an SVG with a set of colors just to throw them away seems quite wasteful. Remapping every pixel of the raster image of every SVG variant seems more inefficient than holding SVG copies.

> This can also apply to icons which are PNGs, so similar behavior would be required for those icons

I would expect users to load and manipulate the PNG themselves before feeding them to `iced`.

**Review by hecrj — APPROVED** [review]
After some more thought, I think this makes sense and it's a useful feature for dealing with icons.

**Comment by mmstick** [comment]
I could try to write a library for parsing and reconstructing and caching SVGs. This was an easier approach since it didn't require writing a library for that.

**Comment by hecrj** [comment]
We already rely on [`usvg`](https://docs.rs/usvg/latest/usvg/) in [`iced_graphics`](https://github.com/iced-rs/iced/blob/8b55e9b9e6ba0b83038dd491dd34d95b4f9a381b/graphics/src/image/vector.rs#L43-L73). We could eventually perform color replacements there, instead of changing the image pixels after rendering.

In any case, I think the feature is useful and the public-facing changes look good.

**Comment by mmstick** [comment]
From what I saw, usvg doesn't support modifying its tree so it would require a round trip to generate a new string and re-parse it from that.

**Comment by hecrj** [comment]
I see :/

I wonder if a color override is something we could eventually contribute to [`resvg`](https://github.com/RazrFalcon/resvg) instead.

**Comment by hecrj** [comment]
Another possibility is performing the color override in the GPU, during texture sampling. This would allow us to store a single copy of the SVG in the cache, and it would work for raster images as well!

**Pull request merged**
